weights: yolov7.pt
cfg: ''
data: /home/ubuntu/flo/roboflow-100-benchmark/yolov7-benchmark/yolov7/washroom-1/data.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 10000
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: roboflow-100/washroom-rf1fa/1
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
world_size: 1
global_rank: -1
save_dir: runs/train/roboflow-100/washroom-rf1fa/1
total_batch_size: 8
